version: '2'
services:
  nginx:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
  springboot-ngnix:
    build:
      context: ./SpringBootNgnix
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - .:/code
    depends_on:
      - nginx
