version: '2'
services:
  nginx:
  container_name: some_nginx
  image: nginx
  restart: always
  ports:
  - 80:80
  volumes:
  - ./nginx/conf.d: /etc/nginx/conf.d
  app:
    restart: always
    build: ./SpringBootNgnix
    working_dir: /SpringBootNgnix
    volumes:
      - ./SpringBootNgnix:/SpringBootNgnix
    expose:
    - "8080"
    command: mvn clean spring-boot:run
    depends_on:
      - nginx
